export const SHOW_LEFT_PANEL = 'SHOW_LEFT_PANEL';
export const ENTER_NOTE_CONTENT = 'ENTER_CONTENT';
export const CREATE_NOTE = 'CREATE_NOTE';
export const OPEN_ADD_NOTE = 'OPEN_ADD_NOTE'
export const CHANGE_ADD_NOTE_COLOR = 'CHANGE_ADD_NOTE_COLOR';
export const GET_ADD_NOTE_INIT_STATE = 'GET_ADD_NOTE_INIT_STATE'
export const CHOOSE_ADD_NOTE_PHOTO = 'CHOOSE_ADD_NOTE_PHOTO';
export const ADD_TO_ARCHIVE = 'ADD_TO_ARCHIVE';
export const ADD_TO_ARCHIVE_IN_NOTE = 'ADD_TO_ARCHIVE_IN_NOTE'


export const CHANGE_NOTE = 'CHANGE_NOTE';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const CHANGE_NOTE_COLOR = 'CHANGE_NOTE_COLOR';

export const DELETE_NOTE = 'DELETE_NOTE';
export const SELECT_NOTE = 'CHOOSE_NOTE';
export const UNSELECT_NOTE = 'UNSELECT_NOTE'

export const ADD_PHOTO_IN_NOTE_COMPONENT = 'ADD_PHOTO_IN_NOTE_COMPONENT';

export const DELETE_NOTE_FOREVER = 'DELETE_NOTE_FROM_FOREVER'

export const SEARCH_NOTE = 'SEARCH_NOTE'
export  const GET_SEARCHED_NOTES = 'GET_SEARCHED_NOTES'
export const CANCEL_SEARCH_NOTE = 'CANCEL_SEARCH_NOTE'

export const CHANGE_FLEX_DIRECTION = 'CHANGE_FLEX_DIRECTION'