export const SET_NOTES  = 'SET_NOTES';
export const SEARCH_NOTES = 'SEARCH_NOTES';
export const CANCEL_SEARCH_NOTE = 'CANCEL_SEARCH_NOTE';

export const OPEN_ADD_NOTE_FORM = 'OPEN_ADD_NOTE_FORM';
export const CHANGE_ADD_NOTE_FORM_INPUT = 'CHANGE_INPUT';
export const CLOSE_ADD_NOTE_FORM = 'CLOSE_ADD_NOTE_FORM';
export const CHANGE_ADD_NOTE_FORM_BACKGROUND = 'CHANGE_ADD_NOTE_FORM_BACKGROUND';
export const CHOOSE_ADD_NOTE_FORM_PICTURE = 'CHOOSE_PICTURE';
export const ADD_NOTE = 'ADD_NOTE';

export const CHANGE_HEADER_TITLE = 'CHANGE_HEADER_TITLE';

export const CHANGE_NOTE_BACKGROUND = 'CHANGE_NOTE_BACKGROUND';
export const ADD_NOTE_TO_ARCHIVE = 'ADD_NOTE_TO_ARCHIVE';
export const ADD_NOTE_TO_TRASH = 'ADD_NOTE_TO_TRASH';
export const RETURN_FROM_ARCHIVE = 'RETURN_FROM_ARCHIVE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const RETURN_FROM_TRASH = 'RETURN_FROM_TRASH';
export const CHOOSE_NOTE = 'CHOOSE_NOTE';
export const DESELECT_NOTE = 'DESELECT_NOTE';
export const CHOOSE_NOTE_PICTURE = 'CHOOSE_NOTE_PICTURE';

export const CLOSE_TOP_PANEL = 'CLOSE_TOP_PANEL';
export const INCREMENT_TOP_PANEL_COUNT = 'INCREMENT_TOP_PANEL_COUNT';

export const OPEN_MODAL_EDIT_FORM = 'OPEN_MODAL_EDIT_FORM';
export const CLOSE_MODAL_EDIT_FORM = 'CLOSE_MODAL_EDIT_FORM';

export const EDIT_NOTE = 'EDIT_NOTE';
export const CHANGE_NOTE_BACKGROUND_IN_MODAL = 'CHANGE_NOTE_BACKGROUND_IN_MODAL';
export const DELETE_IMAGE = 'DELETE_IMAGE';

export const CHANGE_NOTES_DISPLAY = 'CHANGE_NOTES_DISPLAY';
export const OPEN_AND_CLOSE_LEFT_PANEL = 'OPEN_AND_CLOSE_LEFT_PANEL';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_ACTIVE_BTN = 'CHANGE_ACTIVE_BTN';